name: weston-test
base: core22
version: '9.0'
summary: test wayland connection via weston clients
description: none

grade: stable
confinement: strict

parts:
  weston:
    plugin: nil
    stage-packages:
    - weston

apps:
  weston-terminal-test:
    command: usr/bin/weston-terminal
    plugs:
    - wayland
    extensions: [gnome]
  weston-flower-test:
    command: usr/bin/weston-flower
    plugs:
    - wayland
    extensions: [gnome]
